### ISSUE TITLE
Add "bytes guarded" metrics to sdk-go

### ISSUE THREAD

**Issue by sre-is-marcelo** [StanzaSystems/sdk-go#117]
Implement the **bytes matrics** we'll use in our billing process, for each request. Those are:

- bytes received
- bytes accepted
- bytes rejected

Relates Issue: https://github.com/StanzaSystems/sdk-spec/issues/40

**Comment by sre-is-josebiro** [comment]
Passing to @sre-is-msg based on the conversation we had. This needs to turn into a billable metric in Orb.

Context for these metrics captured in this comment from our conversation: https://github.com/StanzaSystems/sdk-spec/issues/40#issuecomment-1839403991

**Comment by sre-is-msg** [comment]
Blocked on making the SDK spec change first: https://github.com/StanzaSystems/sdk-spec/issues/40
