### ISSUE TITLE
Handler / Adaptor for grpc services

### ISSUE THREAD

**Issue by sre-is-josebiro** [StanzaSystems/sdk-go#29]
This issue is to implement an inbound and outbound handler to guard gRPC services, and possibly the adapter (helper functions) as well?

**Comment by sre-is-josebiro** [comment]
Yep, this is an Ignis Launch requirement.

**Comment by sre-is-msg** [comment]
I am starting on this today. Will implement as inbound and outbound gRPC support (and maybe an adapter? TBD on that, gRPC library research required).

**Comment by sre-is-msg** [comment]
- https://github.com/StanzaSystems/sdk-go/pull/72
- https://github.com/StanzaSystems/sdk-go/pull/73

**Comment by sre-is-msg** [comment]
- https://github.com/StanzaSystems/sdk-go/pull/73
- https://github.com/StanzaSystems/sdk-go/pull/74

**Comment by sre-is-msg** [comment]
- https://github.com/StanzaSystems/sdk-go/pull/86

Everything is in place now -- we have a generic guard which is used by the HTTP (inbound and outbound) handlers. The generic guard handles all of the guard logic (checks, metrics, etc) and the HTTP handlers are simple wrappers around that (doing things like checking for HTTP specific response codes and automatically calling `guard.End()` with the correct status).

Creating the gRPC handlers now should be a simple matter of wrapping the generic guard in the same way.

**Comment by sre-is-msg** [comment]
- https://github.com/StanzaSystems/sdk-go/pull/90
