### ISSUE TITLE
API key verification

### ISSUE THREAD

**Issue by niallrmurphy** [StanzaSystems/sdk-go#67]
On a freshly installed sdk-go, with an API key I generated today via the portal, my logs will up with:

```
{"level":"error","ts":1689096551.0486023,"msg":"rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
{"level":"error","ts":1689096551.157478,"msg":"rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
{"level":"error","ts":1689096556.2660632,"msg":"rpc error: code = InvalidArgument desc = error getting apikey: rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
{"level":"error","ts":1689096556.3704655,"msg":"rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
{"level":"error","ts":1689096556.4764822,"msg":"rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
{"level":"error","ts":1689096561.5828202,"msg":"rpc error: code = InvalidArgument desc = error getting apikey: rpc error: code = Unauthenticated desc = Failed to validate X-Stanza-Key header"}
```

I tried pointing it at the demo hub, but it just failed worse:
```

{"level":"error","ts":1689096390.096651,"msg":"rpc error: code = PermissionDenied desc = Not allowed"}
{"level":"error","ts":1689096390.199054,"msg":"rpc error: code = PermissionDenied desc = Not allowed"}
{"level":"error","ts":1689096395.308703,"msg":"rpc error: code = PermissionDenied desc = Not allowed"}
{"level":"error","ts":1689096395.416391,"msg":"rpc error: code = PermissionDenied desc = Not allowed"}
```

Could probably benefit from some more verbose messages about what's going on.

Additionally, if you have a typo in the hub hostname, you don't get a DNS resolution error, which might be worthwhile looking into at some point.

**Comment by sre-is-msg** [comment]
> Additionally, if you have a typo in the hub hostname, you don't get a DNS resolution error, which might be worthwhile looking into at some point.

We're connecting to Hub with a straight-up [grpc.Dial](https://github.com/StanzaSystems/sdk-go/blob/8e1423fd38917fcc33c128d65235e9d3c5525681/stanza/state.go#L169) and it that throws an error we log whatever error is thrown (not sure if it has an error for DNS resolution failing or not, but I an guessing not).

I supposed we could call [net.LookupHost](https://pkg.go.dev/net#LookupHost) before grpc.Dial and log/fail if we can't resolve the given STANZA_HUB_ADDRESS.

**Comment by niallrmurphy** [comment]
Just thinking about it from a user point of view, I would expect that using a bad/fat-fingered hostname as an endpoint, I would get told it was a naming error. I might not be experienced enough with gRPC to figure that out.

**Comment by sre-is-msg** [comment]
API Key generation in portal definitely works (verified by both Andrew and me). I've added an error log message if host fails to resolve DNS: https://github.com/StanzaSystems/sdk-go/commit/72fe82b4172f8d4ef9f5406f7413cb184c7485d2
