### ISSUE TITLE
stops sending metrics to the otel-collector after N hours

### ISSUE THREAD

**Issue by sre-is-andrew** [StanzaSystems/sdk-go#88]
needs more investigation; seems to live for ~24hrs before failing, (possibly an auth renewal?)

**Comment by sre-is-andrew** [comment]
this is still observed

**Comment by sre-is-msg** [comment]
The issue is that -- to use the new bearer token -- we need to shutdown the **existing** Providers and then create new Providers (with the new bearer token). What we are doing right now is to create new Providers but without shutting down the old ones.

**Comment by sre-is-msg** [comment]
https://github.com/StanzaSystems/sdk-go/pull/109
